hash-format = "sha256"

[[files]]
file = "ico64.png"
hash = "fd2e5c07e1bcf84db64fb8cebe46fa3a63301779e54144bc3677b0c4c525f934"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "73b2408a4e00098cf7a97455fe493949808ae1a138c49bec088cbd3c750d6a51"
metafile = true

[[files]]
file = "mods/axolotl-buckets.pw.toml"
hash = "009c9e0e3f0c3e6bb82f3fda9eb3d12ba4692f427ff817d7516c95fc4f8906e5"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "f2f4962bc683bcf0ba922551eaf2b9ca5700f68f84d28ad2d2ca20fe3ac86e41"
metafile = true

[[files]]
file = "mods/beyondenchant.pw.toml"
hash = "360eb5894ba867053e4052e3c903de844ed6f85ebc83f6f89c1d564f028a35f7"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "d1e1775484e4d732f1e7d98aa4c8d317677d16eea620b2b5a28224e0b677b32d"
metafile = true

[[files]]
file = "mods/centered-crosshair.pw.toml"
hash = "ebe8171a86a5c601072c1c59cd4e3bfd88e1da495c3ccd62b51d6a85ce1520fa"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "5aa4a43a151e716fe2f9452b1e22d3696abdf527893e9e4fda17728560ddb2af"
metafile = true

[[files]]
file = "mods/cicada.pw.toml"
hash = "c937442a2f681a7fc883c1526ea97d2e1a117b31586f8fca20b78e7b49dd11c6"
metafile = true

[[files]]
file = "mods/clientsort.pw.toml"
hash = "77a07b79f93cf6566bd537b9dc5021f1644d8e33bfa49b3fb869aaa74aa7abd1"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "67636033c63f8f6e9a67664a23be8e9f2d09206d8c1f8b428d16448a04409a90"
metafile = true

[[files]]
file = "mods/colorful-trims.pw.toml"
hash = "70ab8cc743700f59b5840828e5b40e77515dffe3dafde726f5b8727ddef7308a"
metafile = true

[[files]]
file = "mods/colorize.pw.toml"
hash = "22d7877fc7d51b4685987170bd1032cf038caf2dccf042cc5c3624cf1224fabb"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
hash = "c34570030bef6b982e3e34a14a308cd1be9843368c42e4c68d4a3f2c0c5c2a8f"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "e1879d997a12a832043c0380df086748a51de9688718bfa9c323e68520014858"
metafile = true

[[files]]
file = "mods/deimos.pw.toml"
hash = "20e071aa275d68725f6fca51c8aeaadb9d5cd69918ce2cff4c956b5345c0c213"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "039ad709a142d6103c5b871964c18a8bdf153c13e9074f0c2b91004040476387"
metafile = true

[[files]]
file = "mods/do-a-barrel-roll.pw.toml"
hash = "1ca6aca79f3a7df5f8ecc0ec9aea2d9d0593d794a649695ead25a5772d1fe23c"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
hash = "62a46075494b8b86925602b9d3346d888cd746de47e4b75b903ce8daef53a9ad"
metafile = true

[[files]]
file = "mods/easy-magic.pw.toml"
hash = "4574b91337805ae106722dd247703daf79eb35f171b9beb5aaae84dffc31fe20"
metafile = true

[[files]]
file = "mods/elytra-trims.pw.toml"
hash = "e50cf6945fd4caec1171e923a698fc59d290985f623e461209470f2328281f21"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "29601af9797ce5278e4ad268ac008f320ef9c682a47454a0b35bbeb49db2f4ba"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "0d6d934c9ba9ba3dff000721a47bf389f4ebbebe23a7fd32c7e33dfdf9c9a6b9"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "9a95e1a0f4591173d976753e3f9e93933b87357a468adb42ff1bd8a2702cc7dc"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "216006067453efa7a750f0d8bac6ea84c503b79e40aba32bd77c9edd183ec232"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "178cf4cd755e7547e2e21b15a8b2ca07c4ffb8b35ffb5b3a8f053e9a124051c8"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "c9c2a5b3c98d4b80ac6b24db9a31435f1ec5d95aa4a442c757d83fca0b844088"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "f3c666b7a4140f9944920c8279ba897feb3e7ec48086d9b10862ea9b012aeacb"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "050dffe59c61ded3b3e474cc24c11496d14739ddd3a0efc2ceda22652865eaa7"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "cb330220512be399e4423c39f01f56f8bc413f15b0b5a7fa8079699bcdd133bc"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "f33dbf714c367f859ea2d09dd62cb8da23a8b80b962cc773c9faf6862b6f520f"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "9946fd3c2a85099bb68cff8a2168601c3f1c7879fc42d018171c7cf5f25693d2"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "e0ec01c5bc3591ba368bc2e91c930680fe0e60eec1f18ac3565f432eea01ee6b"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "a91d68c3ac5b08bd79e32dd9f3335fc9a9763afeb7602492cd159351704fccc6"
metafile = true

[[files]]
file = "mods/more-music-discs.pw.toml"
hash = "90b9868db93dc451d42bfdf1c5c9f7b8adc585a0bc3dcf6bc979fb2bba30954f"
metafile = true

[[files]]
file = "mods/moremousetweaks.pw.toml"
hash = "76d80b20c31a2ae585c4baedb56aa510722f327ec2e54b6d9b9405656840c00c"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "5187c8e4e66d8ae594c89368419a56233eb5822ae74ab216e6ce06b87b87cc1a"
metafile = true

[[files]]
file = "mods/music-disc-advancements.pw.toml"
hash = "38fc187d84b5433d6fb6397dcd1f83a188255499921f307e00935a67ca227165"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "e01e4e296bff245a222574cb664cdf07d934356c0de81c6a9ac32a1c9bd25cb2"
metafile = true

[[files]]
file = "mods/no-telemetry.pw.toml"
hash = "f85284ca014edff00024039ba704ac11b2ac989067b5094269449d12e9c3f6a8"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "eff11884e4cb671be3647838865d1882fe746f1c13a115ff5575d0e88c2799c0"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "36256d897025c2dbb168f4da8a0acb726b7f8805c1336971c304fc0f2981363d"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "3338310181c3e44cfc16fa4192356ab4bf16f8103016328b724721574c4b7577"
metafile = true

[[files]]
file = "mods/qraftys-jungle-villages.pw.toml"
hash = "3a63c42dcae966844ec1e7d88ec466c578de557efe858d2b77fda638c6a90d8e"
metafile = true

[[files]]
file = "mods/random-block-placement.pw.toml"
hash = "a375492858135410cfdf95ed48272f0c295708feb706b3973a77ec687e0afc05"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "0914b76224f431905209d67fbfc7c46a846946ee9d24e4b26a3947a6f9fc846c"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "a2e81900be14924e914105f5d0807c57edf1c7317eebce10e5164a60bc67cfd0"
metafile = true

[[files]]
file = "mods/simple-music-control.pw.toml"
hash = "ad92e9f77c6cff0e9e039f39c16ecac7ff1de2a1cd1ee35ef818715a041c9ada"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "1ba5b618f88cf4f76c329db10220ed7f70f06d880d387aff4253d514ed802a3e"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "e66c004401337d03124cb34174f6dab259bf736546659e708de68e3d1ae8986d"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "cdc9a25e16ed4c9bd7f3184b62acc3a5b988b95b0b4fa4852d92ea24029d96f7"
metafile = true

[[files]]
file = "mods/tax-free-levels.pw.toml"
hash = "9de6169c408efb92827c88f57b2e7819d043050a8698013a50a87f93bdc77974"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "5c7435f2a63d49538bd62decf3c801eef84593e540a500b496bd641b98e5ad66"
metafile = true

[[files]]
file = "mods/tool-trims-mod.pw.toml"
hash = "27f9ef377a4c9513b70b18b20230c1bcbe8b42fac828bef7d5c33f8728bd04e9"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "a83cf7d4ae2f7d3ef9cf0789281274a5cfb303716df510c3400bad13590277cc"
metafile = true

[[files]]
file = "mods/unilib.pw.toml"
hash = "81d80c93134e5f9ac8cd8c957d345a6fcbbf97fe5b1fcc558e56f15e42d56613"
metafile = true

[[files]]
file = "mods/xaero-zoomout.pw.toml"
hash = "5cc2bd71c7ad0ad22761a32753ee27e2d7c13f9f9b3466e8f8d595d246e2cd76"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "92fb34687a9dbef14d813840216cc90c21b53860c423e963e4a30ef5603b4613"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "d8d3203ba02dfd3c01b2a1acaae29922b77aa5ccec2a544da0b1f55b071f66c3"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "45f81bda993af1f0a9d418dda93aacbda4bf2ea56f77a9d2845c3536ca630c52"
metafile = true

[[files]]
file = "packwiz-installer-bootstrap.jar"
hash = "a8fbb24dc604278e97f4688e82d3d91a318b98efc08d5dbfcbcbcab6443d116c"
