hash-format = "sha256"

[[files]]
file = "ico64.png"
hash = "fd2e5c07e1bcf84db64fb8cebe46fa3a63301779e54144bc3677b0c4c525f934"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "32180d54da9c59c30b2f9c0a9180e372502ed3b660c00e9863f7b0532250e5d1"
metafile = true

[[files]]
file = "mods/axolotl-buckets.pw.toml"
hash = "038203f7bf63926428eb48f6f6fb7992f93040ab6c08af88647f18b4354e4bcf"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "2331b58e76f1d752d7843242a1a6e569737dde06b429dc33c1bc9cf6ef97ffd9"
metafile = true

[[files]]
file = "mods/beyondenchant.pw.toml"
hash = "3e7eeffed207728861ae6e52d18235874e12bdbcfd9a0b16d3b3cc5ac7096893"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "22a43e73b45c13eb468c9d29dc0324233ecc6aa7b5bcc4c403332fa5d2540c23"
metafile = true

[[files]]
file = "mods/centered-crosshair.pw.toml"
hash = "da471c22b6e9aded0bf6f19d62eb1463d57a49240818cfb5e9bbcf5b6bf0462e"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "d808912df375a4591e8fbfe343f5d5de36c54c7171bdd579665189d3adb5d79c"
metafile = true

[[files]]
file = "mods/cicada.pw.toml"
hash = "f4fd56d00f729e121f33f37eee37fdcf3ba65368f330ca7a32778a3768f30412"
metafile = true

[[files]]
file = "mods/clientsort.pw.toml"
hash = "efba778e0681685a4e47849156e396fc1f8f606d0dc5330dd9c2b801895e675b"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "d5f3469bdda0c2f230ccbc471b6cc482a949d4a897e5fbf6155e1877f18a9b99"
metafile = true

[[files]]
file = "mods/colorful-trims.pw.toml"
hash = "f324e8a1f495b064123b086fa61cc155112eb14bb6c8bc78795754d0a375c1c9"
metafile = true

[[files]]
file = "mods/colorize.pw.toml"
hash = "d141d071f879970c697df9afeadf43d436ec1adf8044c55fa419c9b4adaf21cb"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
hash = "1cfd1331ee83eb8e949b37335eac979fb8aa4c37ac8f7b1b3ef3463250931ba5"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "7538aa53664a743a869263277b3beb0ed6d39d2ef044e085dbd750774509c561"
metafile = true

[[files]]
file = "mods/deimos.pw.toml"
hash = "f5c125e5e2305ccf453508d65536d50c573b698db4d5028f71db2051de6419fd"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "50dbce7d57e047ed636ff7112746cf317ab11a1cf1772b7c408edfa29d550e06"
metafile = true

[[files]]
file = "mods/do-a-barrel-roll.pw.toml"
hash = "417e3891ee4c07c2e50a52e27ab1d64847421abf10504465560f9228d84a507d"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
hash = "9ebb1f808ce018c07eff3d4e5ba91e64df69320f2d4bebde12ff6ac5dc844473"
metafile = true

[[files]]
file = "mods/easy-magic.pw.toml"
hash = "2093b9294959ecc873ec8bc3fdd2fdb1766ddb800f6f6d5d9f8f318b45a66df3"
metafile = true

[[files]]
file = "mods/elytra-trims.pw.toml"
hash = "671e2561d2eb441f69fe66da261a46975742c6d9b6c885979118a846e79b3224"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "b107fbba64b365e82deff591eeeed64e98d62ca37b3b582336bbc63b703175de"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "4c6853793af0c94eaa0c7d6be22fe05b449437f79538a3869f3e126de524c25c"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "aee2a338c197ae176e7e7737292c3fe5fc2a6fbbc5a7d7d22bec588659fd3300"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "bf60e9b23fe38e99d24ec584b108b89c803deb06993844fd0ecf5928d970e98c"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "79eb5a22a2ad51d0b9d1b919e62caacc1bb00451f318629f07fa3e2b0f93844f"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "7c9187398e2b4fd78e1b2b6c89395a40ebde920a3b958c3f2b37cb6c8dd84983"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "d3e13603ce06fd1565821d98a8752ad261d3fd7075589841dcf77d30c726a190"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "ed640cf1f394b921744669134cbea337f2ddedea1025166c4564e5435e7ca994"
metafile = true

[[files]]
file = "mods/ledger.pw.toml"
hash = "01d35ed6fc7c97e012273dda3a1fc960583296dc7753257191b842a11cb01a14"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "ee835f4dc551160d981cb557f1275f7ecde0487f61213490835009ff722e0016"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "2d4769eb4119243590fdd6b1482480ded6e20ac61c0b7a811d9b7ac0aa733dd7"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "b2c0a13e703b462a28a2d2064ac62d1138c240c003d9bd0d3511914cd066ae80"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "489dadb4f18b3320be27553e8f9da784fda9539b297d3c038da3f4756b2100b8"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "481acb6ee66b2a8de7dc3259ccd6417d2bbd49ae979b0e252e81c4ef33a4a0b3"
metafile = true

[[files]]
file = "mods/more-music-discs.pw.toml"
hash = "9ae2e621af191a702287271ef285fa9fc73300c1a3109c49015cc0bddad71195"
metafile = true

[[files]]
file = "mods/moremousetweaks.pw.toml"
hash = "084f793ea637096e9c47f9a1ae413cefa399b26f25046c95c4012e7eb83473ea"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "e025c02c481aaf9fc84dd702f02dd59f77078124955cf282e799607d8a627214"
metafile = true

[[files]]
file = "mods/music-disc-advancements.pw.toml"
hash = "8628badeedff0bcbc87809aebd89395373343831ecf277881ad4789cadae3d87"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "94250075119aee5c9b7dfb13b4486aee68d8e2697a3a7f9a56e7e42b00fa7ae4"
metafile = true

[[files]]
file = "mods/no-telemetry.pw.toml"
hash = "4c556755302db0ad5494b5b3eb0ded1435ab74aa1cacb98d7dc5408bb6422440"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "480874117f964bfb861f0a67dae31886458b1dc9bc1146d65633f0e8ac6c8c14"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "76f73e4a0666d398e75aa0889baa1fd9f77f46210703c7f95ce0c7638218725b"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "4e114619ceabbd2f44e8068d879e425c9fdb8c7337e0b6a1caae46f5fc69f560"
metafile = true

[[files]]
file = "mods/qraftys-jungle-villages.pw.toml"
hash = "e6c0a515ef1bacedd11971235598a71cdea656c9ad62cb56e372dfd38d105073"
metafile = true

[[files]]
file = "mods/random-block-placement.pw.toml"
hash = "27a5dd69a8c48194f376c46d57a1ce9252091b9bf5bd5135aa611af7db358388"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "2b7e3124f0204a8762fcdfa844915316983bc5f125107a81e33df96de17ab2bf"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "ffb96b4865036c4baab239ff6c3d52b8997f0180df95163b63bfaabca6b1d633"
metafile = true

[[files]]
file = "mods/simple-music-control.pw.toml"
hash = "c4ef650f6a5465cb8d3fe33c005093c45798a913bb21f92f1730e2a3e2c5d3fb"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "805ad8ba983c851c450e0bb3c9ae98ac05dc299d4ef049d0a8353e15a34c6864"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "967cba5aa40d4f98462bef4031c58a0faed33e7c02fb6a47a80b879bdfca7936"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "b53d69c11b5f190b3f44d5ac41092ee949ebdc927503f365d09ee869f897aeac"
metafile = true

[[files]]
file = "mods/tax-free-levels.pw.toml"
hash = "f5f26ca2f093b9f461226702e4cfb89d7a4e09dd4a3ed171af14d087641937c1"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "3cc5b94dd9117c4602285b1e23df0090d87e7c7733c49ee0b76bda84211d8b25"
metafile = true

[[files]]
file = "mods/tool-trims-mod.pw.toml"
hash = "b96f021dbbf9a0a230668535cd9f099b7471540212a25150a06745af2c51a85b"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "f6cdcfc5d09dd6226ff10d53d2da0b7abefa7ec5fac7871456f11ba8c81fa1c0"
metafile = true

[[files]]
file = "mods/unilib.pw.toml"
hash = "c55c3b40f5e59a28a28462b8ee1019ef68d690c6059b67cf2038929eaa89c35f"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "b6637110509503de5c77ce30430a21a4d2570d33c8589087f9384eb04995ec3e"
metafile = true

[[files]]
file = "mods/xaero-zoomout.pw.toml"
hash = "b9f8c2b1230128dcb7f5ff71ddcffc0973aee470901cb1ba9223bda3ee5ae6dc"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "b930feedb63f87b43ef048b6ac332be9eb6ce8be76f1d6f01968e61725401246"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "b8babb79ff6ceaf0e68ef69dcdeb1d3922b04aebc814774745a7302bb4cfb329"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "79eb459ff37198494b6bda8e6c89a7a1f4977d7fbbd5478d49d03424b3d3e82b"
metafile = true

[[files]]
file = "packwiz-installer-bootstrap.jar"
hash = "a8fbb24dc604278e97f4688e82d3d91a318b98efc08d5dbfcbcbcab6443d116c"
