name = "Funky Hardcore MC"
author = "FunkyChickenMC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7a2c83c3644345c8b99a679c07b7cd52a39b46ab9d33bd16d6f8938c5951d77"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
