name = "Funky Hardcore MC"
author = "FunkyChickenMC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d975fdafeb6962a67c0a7db84e1360f83ed3e0e20502aa61cd2ea32d087ee9e"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
